-- Frozen PostgreSQL SQL generated from protected-main QuotationService migrations
-- 20260829074943_AddAcceptedQuotationOutcome and 20260830071526_PreserveOutcomeTimestampPrecision at bd201a5.
CREATE TABLE "QuotationAcceptedOutcome" (
    "ID" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "EventKey" character varying(128) NOT NULL,
    "QuotationID" integer NOT NULL,
    "SourceRequestID" integer NULL,
    "SourceJourneyID" uuid NULL,
    "AcceptedUtc" timestamp without time zone NOT NULL,
    "AcceptanceOrigin" character varying(16) NOT NULL,
    CONSTRAINT "PK_QuotationAcceptedOutcome" PRIMARY KEY ("ID")
);
CREATE INDEX "IX_QuotationAcceptedOutcome_AcceptedUtc" ON "QuotationAcceptedOutcome" ("AcceptedUtc");
CREATE UNIQUE INDEX "IX_QuotationAcceptedOutcome_EventKey" ON "QuotationAcceptedOutcome" ("EventKey");
CREATE INDEX "IX_QuotationAcceptedOutcome_QuotationID" ON "QuotationAcceptedOutcome" ("QuotationID");
CREATE INDEX "IX_QuotationAcceptedOutcome_SourceJourneyID" ON "QuotationAcceptedOutcome" ("SourceJourneyID");
CREATE INDEX "IX_QuotationAcceptedOutcome_SourceRequestID" ON "QuotationAcceptedOutcome" ("SourceRequestID");
ALTER TABLE "QuotationAcceptedOutcome" ADD "AcceptedUtcSubMicrosecondTicks" smallint NOT NULL DEFAULT 0;
