using Npgsql;

namespace Legacy.Maliev.DataMigration.Tests;

[Collection(PostgreSqlAdapterTestGroup.Name)]
public sealed class ApprovedSourceDispositionTargetIntegrationTests(PostgreSqlAdapterFixture fixture)
{
    [Fact]
    public async Task QuotationDisposition_RejectsOrdinaryCopy_AndMatchesReviewedTargetSchema()
    {
        TableCopyPlan[] sourceTables =
        [
            ApprovedSourceDispositionManifestTests.Outbox(CurrentQuotationSourceContract.GoogleAnalyticsOutbox,
                "PK_GoogleAnalyticsOutbox", "UX_GoogleAnalyticsOutbox_EventKey", uniqueIndex: true),
            ApprovedSourceDispositionManifestTests.Outbox(CurrentQuotationSourceContract.QuotationOutcomeOutbox,
                "PK_QuotationOutcomeOutbox", "UQ_QuotationOutcomeOutbox_EventKey", uniqueIndex: false),
        ];
        var draft = new DatabaseSchemaPlan("Quotation", "1.0", new string('a', 64), new string('0', 64), sourceTables)
        {
            SourceDispositionProfile = ApprovedSourceDispositionManifest.QuotationOutboxesV1,
            SourceTableDispositions = ApprovedSourceDispositionManifest.DispositionsForDatabase("Quotation", sourceTables),
        };
        DatabaseSchemaPlan sourcePlan = draft with { TargetSchemaSha256 = PostgreSqlSchemaFingerprint.ComputeExpected(draft) };
        DatabaseSchemaPlan targetDraft = sourcePlan with
        {
            Tables = ApprovedSourceDispositionManifest.TargetTablesFor(sourcePlan),
            SourceDispositionProfile = null,
            SourceTableDispositions = [],
        };
        DatabaseSchemaPlan targetPlan = targetDraft with
        {
            TargetSchemaSha256 = PostgreSqlSchemaFingerprint.ComputeExpected(targetDraft),
        };
        Assert.Equal(sourcePlan.TargetSchemaSha256, targetPlan.TargetSchemaSha256);

        PostgreSqlShadowTarget target = fixture.CreateShadowTarget();
        ShadowDatabase shadow = await target.CreateUniqueEmptyShadowAsync("Quotation",
            $"legacy_shadow_quote_{Guid.NewGuid():N}", Guid.NewGuid().ToString("D"), CancellationToken.None);
        try
        {
            await using (IPostgreSqlWholeDatabaseTransaction rejected =
                await target.BeginWholeDatabaseTransactionAsync(shadow, CancellationToken.None))
            {
                MigrationExecutionException failure = await Assert.ThrowsAsync<MigrationExecutionException>(() =>
                    rejected.ApplySchemaAsync(sourcePlan, CancellationToken.None));
                Assert.Equal("source_disposition_schema_application_not_ready", failure.Code);
                MigrationExecutionException finalization = await Assert.ThrowsAsync<MigrationExecutionException>(() =>
                    rejected.FinalizeSchemaAsync(sourcePlan, CancellationToken.None));
                Assert.Equal("source_disposition_schema_application_not_ready", finalization.Code);
            }

            {
                await using IPostgreSqlWholeDatabaseTransaction transaction =
                    await target.BeginWholeDatabaseTransactionAsync(shadow, CancellationToken.None);
                await transaction.ApplySchemaAsync(targetPlan, CancellationToken.None);
                await transaction.FinalizeSchemaAsync(targetPlan, CancellationToken.None);
                Assert.Equal(sourcePlan.TargetSchemaSha256,
                    await transaction.InspectSchemaAsync(sourcePlan, CancellationToken.None));
            }

            var connectionBuilder = new NpgsqlConnectionStringBuilder(fixture.ShadowAdminConnectionString)
            {
                Database = shadow.Name,
            };
            await using var connection = new NpgsqlConnection(connectionBuilder.ConnectionString);
            await connection.OpenAsync();
            string efSql = await File.ReadAllTextAsync(Path.Combine(AppContext.BaseDirectory, "Fixtures",
                "Quotation", "bd201a5-quotation-accepted-outcome.sql"));
            TableCopyPlan archive = targetPlan.Tables.Single(table => table.TargetSchema == "legacy_compatibility");
            string archiveColumns = string.Join(", ", archive.OrderedColumns.Select(column =>
                $"\"{column}\" {archive.ColumnTypes[column]}" +
                (archive.Identities.Any(identity => identity.Column == column) ? " GENERATED BY DEFAULT AS IDENTITY" : string.Empty) +
                (archive.NullableColumns.Contains(column) ? string.Empty : " NOT NULL")));
            await using (var create = new NpgsqlCommand($"""
                CREATE SCHEMA legacy_compatibility;
                CREATE TABLE legacy_compatibility."GoogleAnalyticsOutbox" ({archiveColumns},
                    CONSTRAINT "PK_GoogleAnalyticsOutbox" PRIMARY KEY ("ID"));
                CREATE UNIQUE INDEX "UX_GoogleAnalyticsOutbox_EventKey"
                    ON legacy_compatibility."GoogleAnalyticsOutbox" ("EventKey");
                {efSql}
                """, connection))
            {
                _ = await create.ExecuteNonQueryAsync();
            }
            await using IPostgreSqlWholeDatabaseTransaction efObserved =
                await target.BeginWholeDatabaseTransactionAsync(shadow, CancellationToken.None);
            Assert.Equal(sourcePlan.TargetSchemaSha256,
                await efObserved.InspectSchemaAsync(sourcePlan, CancellationToken.None));
        }
        finally
        {
            await target.DeleteRunOwnedShadowAsync(shadow, CancellationToken.None);
        }
    }
}
