using System.Globalization;
using System.Security.Cryptography;
using Npgsql;
using Testcontainers.PostgreSql;

namespace Legacy.Maliev.DataMigration.Tests;

[CollectionDefinition(Name, DisableParallelization = true)]
public sealed class LocalSchemaAlignmentDisposableProofGroup
{
    public const string Name = "LOCAL schema alignment disposable proof";
}

/// <summary>
/// Synthetic disposable experiments for #218. These prove repair mechanics, not a live
/// schema authority, signed exact-23 reconciliation, or permission to change a shared target.
/// </summary>
[Collection(LocalSchemaAlignmentDisposableProofGroup.Name)]
public sealed class LocalSchemaAlignmentDisposableProofTests : IAsyncLifetime
{
    private readonly PostgreSqlContainer _container = new PostgreSqlBuilder("postgres:18-alpine")
        .WithDatabase("postgres")
        .WithPassword(Convert.ToHexString(RandomNumberGenerator.GetBytes(24)))
        .WithCreateParameterModifier(parameters =>
        {
            foreach (var bindings in parameters.HostConfig!.PortBindings!.Values)
            {
                foreach (var binding in bindings)
                {
                    binding.HostIP = "127.0.0.1";
                }
            }
        }).Build();

    private string ConnectionString => new NpgsqlConnectionStringBuilder(_container.GetConnectionString())
    {
        Host = "127.0.0.1",
        Pooling = false,
    }.ConnectionString;

    public Task InitializeAsync()
    {
        return _container.StartAsync();
    }

    public async Task DisposeAsync()
    {
        await _container.DisposeAsync();
    }

    [Theory]
    [InlineData(false)]
    [InlineData(true)]
    public async Task Collation_rebuild_preserves_rows_and_sequence_or_rolls_back_collision(bool collision)
    {
        await using var connection = new NpgsqlConnection(ConnectionString);
        await connection.OpenAsync();
        await using (var seed = new NpgsqlCommand("""
            CREATE COLLATION public."legacy_ci_as"
                (provider = icu, locale = 'und-u-ks-level2', deterministic = false);
            CREATE TABLE public."Probe" ("Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Name" text NOT NULL UNIQUE);
            INSERT INTO public."Probe" ("Name") VALUES ('a');
            """, connection))
        {
            _ = await seed.ExecuteNonQueryAsync();
        }
        await using (var insert = new NpgsqlCommand("INSERT INTO public.\"Probe\" (\"Name\") VALUES ($1)", connection))
        {
            _ = insert.Parameters.AddWithValue(collision ? "A" : "b");
            _ = await insert.ExecuteNonQueryAsync();
        }
        string before = await SnapshotAsync(connection);
        var table = new TableCopyPlan("dbo", "Probe", "public", "Probe", ["Id", "Name"], ["Id"])
        {
            ColumnTypes = new Dictionary<string, string> { ["Id"] = "integer", ["Name"] = "text" },
            Identities = [new("Id", 1, 1, 2, true)],
            PrimaryKey = new("Probe_pkey", ["Id"]),
            UniqueConstraints = [new("Probe_Name_key", ["Name"])],
        };
        var preimage = new DatabaseSchemaPlan("postgres", "1.0", new string('a', 64), "", [table]);
        preimage = preimage with { TargetSchemaSha256 = PostgreSqlSchemaFingerprint.ComputeExpected(preimage) };
        ProductionSchemaObservation beforeSchema = await ProductionSchemaCatalogInspector.InspectDatabaseAsync(
            preimage, ConnectionString, CancellationToken.None);
        Assert.Equal(preimage.TargetSchemaSha256, beforeSchema.SchemaSha256);
        await using var transaction = await connection.BeginTransactionAsync();
        await using var alter = new NpgsqlCommand("""
            ALTER TABLE public."Probe" ALTER COLUMN "Name"
                TYPE text COLLATE public."legacy_ci_as" USING "Name"::text;
            """, connection, transaction);
        if (collision)
        {
            PostgresException error = await Assert.ThrowsAsync<PostgresException>(
                alter.ExecuteNonQueryAsync);
            Assert.Equal(PostgresErrorCodes.UniqueViolation, error.SqlState);
            await transaction.RollbackAsync();
        }
        else
        {
            _ = await alter.ExecuteNonQueryAsync();
            await transaction.CommitAsync();
        }
        Assert.Equal(before, await SnapshotAsync(connection));
        DatabaseSchemaPlan final = collision ? preimage : preimage with
        {
            Tables = [table with { Collations = new Dictionary<string, string> { ["Name"] = "legacy_ci_as" } }],
        };
        final = final with { TargetSchemaSha256 = PostgreSqlSchemaFingerprint.ComputeExpected(final) };
        ProductionSchemaObservation afterSchema = await ProductionSchemaCatalogInspector.InspectDatabaseAsync(
            final, ConnectionString, CancellationToken.None);
        Assert.Equal(final.TargetSchemaSha256, afterSchema.SchemaSha256);
        await using var collation = new NpgsqlCommand("""
            SELECT co.collname FROM pg_attribute a JOIN pg_collation co ON co.oid=a.attcollation
            WHERE a.attrelid='public."Probe"'::regclass AND a.attname='Name';
            """, connection);
        Assert.Equal(collision ? "default" : "legacy_ci_as", await collation.ExecuteScalarAsync());
        await using var unique = new NpgsqlCommand("""
            SELECT count(*) FROM pg_index WHERE indrelid='public."Probe"'::regclass AND indisunique AND indisvalid;
            """, connection);
        Assert.Equal(2L, await unique.ExecuteScalarAsync());
    }

    [Theory]
    [InlineData("2026-10-01T09:04:00.1234567+07:00")]
    [InlineData("2026-10-01T09:04:00.1234569-03:30")]
    public async Task Lockout_projection_retains_original_text_and_truncates_instead_of_rounding(string exact)
    {
        DateTimeOffset parsed = DateTimeOffset.ParseExact(exact, "yyyy-MM-dd'T'HH:mm:ss.fffffffzzz",
            CultureInfo.InvariantCulture);
        DateTime projected = new(parsed.UtcTicks - (parsed.UtcTicks % 10), DateTimeKind.Utc);
        await using var connection = new NpgsqlConnection(ConnectionString);
        await connection.OpenAsync();
        await using (var seed = new NpgsqlCommand("""
            CREATE TABLE public."AspNetUsers" ("Id" text PRIMARY KEY, "LockoutEnd" text);
            """, connection))
        {
            _ = await seed.ExecuteNonQueryAsync();
        }
        await using (var seedRows = new NpgsqlCommand(
            "INSERT INTO public.\"AspNetUsers\" VALUES ('active', $1), ('nullable', NULL);", connection))
        {
            _ = seedRows.Parameters.AddWithValue(exact);
            _ = await seedRows.ExecuteNonQueryAsync();
        }
        await using var transaction = await connection.BeginTransactionAsync();
        await using (var repair = new NpgsqlCommand("""
            CREATE SCHEMA legacy_migration_internal;
            CREATE TABLE legacy_migration_internal."AspNetUserLockoutEndExact" AS
                SELECT "Id" AS "UserId", "LockoutEnd" AS "ExactValue" FROM public."AspNetUsers";
            ALTER TABLE public."AspNetUsers" ALTER COLUMN "LockoutEnd"
                TYPE timestamp with time zone USING NULL::timestamp with time zone;
            """, connection, transaction))
        {
            _ = await repair.ExecuteNonQueryAsync();
        }
        await using (var project = new NpgsqlCommand(
            "UPDATE public.\"AspNetUsers\" SET \"LockoutEnd\"=$1 WHERE \"Id\"='active';", connection, transaction))
        {
            _ = project.Parameters.AddWithValue(projected);
            _ = await project.ExecuteNonQueryAsync();
        }
        await transaction.CommitAsync();
        await using var readback = new NpgsqlCommand("""
            SELECT u."LockoutEnd", e."ExactValue" FROM public."AspNetUsers" u
            JOIN legacy_migration_internal."AspNetUserLockoutEndExact" e ON e."UserId"=u."Id"
            ORDER BY u."Id";
            """, connection);
        await using var reader = await readback.ExecuteReaderAsync();
        Assert.True(await reader.ReadAsync());
        Assert.Equal(projected, reader.GetDateTime(0));
        Assert.Equal(exact, reader.GetString(1));
        Assert.Equal(parsed.UtcTicks % 10, parsed.UtcTicks - reader.GetDateTime(0).Ticks);
        Assert.True(await reader.ReadAsync());
        Assert.True(reader.IsDBNull(0));
        Assert.True(reader.IsDBNull(1));
        Assert.False(await reader.ReadAsync());
    }

    [Fact]
    public async Task Disposable_restart_preserves_rows_and_uses_a_fresh_connection()
    {
        await using var before = new NpgsqlConnection(ConnectionString);
        DateTime oldStart;
        try
        {
            await before.OpenAsync();
            await using (var seed = new NpgsqlCommand("""
                CREATE TABLE public."RestartProbe" ("Id" integer PRIMARY KEY);
                INSERT INTO public."RestartProbe" VALUES (42);
                """, before))
            {
                _ = await seed.ExecuteNonQueryAsync();
            }
            await using (var start = new NpgsqlCommand("SELECT pg_postmaster_start_time();", before))
            {
                oldStart = (DateTime)(await start.ExecuteScalarAsync())!;
            }
            await before.CloseAsync();
            await _container.StopAsync();
            await _container.StartAsync();
            await using var after = new NpgsqlConnection(ConnectionString);
            await after.OpenAsync();
            await using var readback = new NpgsqlCommand(
                "SELECT \"Id\", pg_postmaster_start_time() FROM public.\"RestartProbe\";", after);
            await using var reader = await readback.ExecuteReaderAsync();
            Assert.True(await reader.ReadAsync());
            Assert.Equal(42, reader.GetInt32(0));
            Assert.NotEqual(oldStart, reader.GetDateTime(1));
            Assert.False(await reader.ReadAsync());
        }
        finally
        {
            // Only this random-credential disposable pool; never clear application pools.
            NpgsqlConnection.ClearPool(before);
        }
    }

    [Fact]
    public async Task Disposable_replacement_on_reused_endpoint_observes_new_identity_and_rows()
    {
        string connectionString = ConnectionString;
        var settings = new NpgsqlConnectionStringBuilder(connectionString);
        string oldIdentity;
        await using (var before = new NpgsqlConnection(connectionString))
        {
            await before.OpenAsync();
            await using var identity = new NpgsqlCommand("SELECT system_identifier::text FROM pg_control_system();", before);
            oldIdentity = (string)(await identity.ExecuteScalarAsync())!;
        }
        // Reuse only this test's dynamically allocated loopback port after stopping
        // its original container. No persistent target or shared test port is used.
        await _container.StopAsync();
        await using var replacement = new PostgreSqlBuilder("postgres:18-alpine")
            .WithDatabase(settings.Database!)
            .WithPassword(settings.Password!)
            .WithPortBinding(settings.Port, 5432)
            .WithCreateParameterModifier(parameters =>
            {
                foreach (var bindings in parameters.HostConfig!.PortBindings!.Values)
                {
                    foreach (var binding in bindings) { binding.HostIP = "127.0.0.1"; }
                }
            }).Build();
        await replacement.StartAsync();
        Assert.Equal(settings.Port, replacement.GetMappedPublicPort(5432));
        await using var after = new NpgsqlConnection(connectionString);
        await after.OpenAsync();
        await using var readback = new NpgsqlCommand("SELECT system_identifier::text FROM pg_control_system();", after);
        string newIdentity = (string)(await readback.ExecuteScalarAsync())!;
        Assert.NotEqual(oldIdentity, newIdentity);
        await using var seed = new NpgsqlCommand("""
            CREATE TABLE public."ReplacementProbe" ("Id" integer PRIMARY KEY);
            INSERT INTO public."ReplacementProbe" VALUES (84);
            """, after);
        _ = await seed.ExecuteNonQueryAsync();
        await using var row = new NpgsqlCommand("SELECT \"Id\" FROM public.\"ReplacementProbe\";", after);
        Assert.Equal(84, await row.ExecuteScalarAsync());
    }

    private static async Task<string> SnapshotAsync(NpgsqlConnection connection)
    {
        await using var command = new NpgsqlCommand("""
            SELECT (SELECT string_agg("Id"::text || ':' || encode(convert_to("Name", 'UTF8'), 'hex'), ',' ORDER BY "Id")
                FROM public."Probe") || '|' || last_value::text || '|' || is_called::text
            FROM public."Probe_Id_seq";
            """, connection);
        return (string)(await command.ExecuteScalarAsync())!;
    }
}
